/**
 * Capture cues. Audio is the primary feedback channel during a session: it
 * works when the screen doesn't — facing away, mid-follow-through, walking back
 * to the mark — so every state change has a distinct sound.
 *
 * expo-audio ships a web implementation too, so this one file serves both.
 */
import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';

import { CueAudio, CueName } from './types';

// Generated by scripts/gen-tones.mjs: delivery is a single soft 880 Hz, alert a
// low double buzz, end a falling pair, done a rising pair.
const SOURCES: Record<CueName, number> = {
  delivery: require('../../assets/audio/delivery.wav'),
  alert: require('../../assets/audio/alert.wav'),
  end: require('../../assets/audio/end.wav'),
  done: require('../../assets/audio/done.wav'),
};

export function createCueAudio(): CueAudio {
  let players: Partial<Record<CueName, AudioPlayer>> = {};

  return {
    async prepare() {
      try {
        // Cues must sound at a net even with the ringer off, and must not stop
        // whatever else the bowler is playing.
        await setAudioModeAsync({
          playsInSilentMode: true,
          interruptionMode: 'mixWithOthers',
          shouldPlayInBackground: true,
        });
      } catch {
        // An unavailable audio session is not a reason to abandon the session;
        // the visual state still carries the meaning.
      }
      for (const cue of Object.keys(SOURCES) as CueName[]) {
        if (players[cue]) continue;
        try {
          players[cue] = createAudioPlayer(SOURCES[cue]);
        } catch {
          // Leave it unset — play() below degrades to silence.
        }
      }
    },

    play(cue: CueName) {
      const player = players[cue];
      if (!player) return;
      try {
        // Re-fire from the top; a cue may land while the previous one rings.
        void player.seekTo(0);
        player.play();
      } catch {
        // Never let a missed tone interrupt a spell.
      }
    },

    release() {
      for (const player of Object.values(players)) {
        try {
          player?.remove();
        } catch {
          // Already gone.
        }
      }
      players = {};
    },
  };
}
